//! Agent sandbox policy daemon entry point.

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use agent_sandbox_policyd::{PolicyServer, PolicyStore, PolicydArgs, PolicydError};
use clap::Parser;

#[derive(Parser, Debug)]
#[command(
    name = "agent-sandbox-policyd",
    version,
    about = "Policy daemon that brokers prompts between sandboxed agents and host UI clients",
    long_about = "Long-lived policy daemon for the agent sandbox stack.\n\n\
        Listens on a host-side Unix socket for UI clients (agent-sandbox-approve, \
        agent-sandbox-ui) and on a separate sandbox-side socket for components running \
        inside the bwrap mount namespace (agent-sandbox-nfq, agent-sandbox-syscall-arm, \
        agent-sandbox-fs-arm). Merges declarative policy, per-project policy, and \
        per-session rules into a unified verdict store, then answers Check/Elevate/\
        Filesystem requests and prompts the user for interactive approvals.\n\n\
        EXAMPLES:\n\
        # Run with default NixOS paths.\n\
        agent-sandbox-policyd\n\n\
        # Override the host socket and load policy from a custom JSON file.\n\
        agent-sandbox-policyd \\\n\
            --socket /run/agent-sandbox/policy.sock \\\n\
            --declarative /home/user/.config/agent-sandbox/declarative.json\n\n\
        # Use interactive approval with a longer timeout and a Nix expression export.\n\
        agent-sandbox-policyd \\\n\
            --approval-timeout 600 \\\n\
            --export-nix /var/lib/agent-sandbox/exported-policy.nix"
)]
struct Cli {
    /// Host-side Unix socket path. UI clients (agent-sandbox-approve, agent-sandbox-ui) connect here to register and receive prompts.
    #[arg(
        long,
        value_name = "SOCKET",
        default_value = "/run/agent-sandbox/policy.sock"
    )]
    socket: PathBuf,

    /// Sandbox-side Unix socket path. Components running inside the bwrap mount namespace (agent-sandbox-nfq, agent-sandbox-syscall-arm, agent-sandbox-fs-arm) connect here. Must differ from the host socket.
    #[arg(
        long,
        value_name = "SOCKET",
        default_value = "/run/agent-sandbox/sandbox-policy.sock"
    )]
    sandbox_socket: PathBuf,

    /// Optional Unix socket used only by the trusted transparent HTTP proxy.
    #[arg(long, value_name = "SOCKET", env = "AGENT_SANDBOX_PROXY_SOCKET")]
    proxy_socket: Option<PathBuf>,

    /// Optional Unix group ID allowed to access the trusted proxy socket.
    #[arg(long, value_name = "GID", env = "AGENT_SANDBOX_PROXY_GID")]
    proxy_gid: Option<u32>,

    /// Declarative policy JSON file. The lowest-priority policy layer, typically generated by the NixOS module from "agent-sandbox.declarative" settings.
    #[arg(
        long,
        value_name = "PATH",
        default_value = "/etc/agent-sandbox/declarative.json"
    )]
    declarative: PathBuf,

    /// Where the merged policy is written as JSON on startup. Consumed by the bwrap wrapper and by "agent-sandbox-nfq" to bootstrap the in-kernel deny list.
    #[arg(
        long,
        value_name = "PATH",
        default_value = "/var/lib/agent-sandbox/exported-policy.json"
    )]
    export_json: PathBuf,

    /// Optional path to also export the merged policy as a Nix attribute set expression. Empty (the default) disables the Nix export. Used by NixOS rebuilds to regenerate "environment.etc.\"agent-sandbox/policy.nix\"".
    #[arg(long, value_name = "PATH", default_value = "")]
    export_nix: String,

    /// How long (in seconds) to wait for a UI client to answer an approval prompt before denying the request. Fractional values are accepted. The effective wait is clamped to at least 1 second.
    #[arg(long, value_name = "SECONDS", default_value = "300")]
    approval_timeout: f64,

    /// Allow UI clients to receive interactive approval prompts. When disabled, all non-declarative requests are denied without prompting. Useful for headless or CI sandboxes.
    #[arg(long = "no-interactive-approval", action = clap::ArgAction::SetFalse, default_value_t = true)]
    interactive_approval: bool,

    /// Path to the "agent-sandbox-ui" binary. If unset, the daemon falls back to the env var `AGENT_SANDBOX_UI_SPAWN_CMD`, then to a built-in default. Used when policyd needs to spawn a transient UI client for a request that arrived with no registered UI.
    #[arg(long, value_name = "PATH", env = "AGENT_SANDBOX_UI_SPAWN_CMD")]
    ui_spawn_cmd: Option<PathBuf>,

    /// Path to the "agent-sandbox-fsmon" binary. If unset, the daemon falls back to the env var `AGENT_SANDBOX_FS_MONITOR_CMD`. Used when an "agent-sandbox-fs-arm" request asks for a fanotify monitor to be started in the host mount namespace.
    #[arg(long, value_name = "PATH", env = "AGENT_SANDBOX_FS_MONITOR_CMD")]
    fs_monitor_cmd: Option<PathBuf>,

    /// Path to the "agent-sandbox-syscall-broker" binary. If unset, the daemon falls back to the env var `AGENT_SANDBOX_SYSCALL_BROKER_CMD`. Used when an "agent-sandbox-syscall-arm" request needs a host-side seccomp user-notification handler to be spawned.
    #[arg(long, value_name = "PATH", env = "AGENT_SANDBOX_SYSCALL_BROKER_CMD")]
    syscall_broker_cmd: Option<PathBuf>,
    
    /// Remove stale cgroup freezer state after the policy service stops.
    #[arg(long, hide = true)]
    cleanup_cgroup_freeze: bool,
}

#[tokio::main]
async fn main() -> Result<(), PolicydError> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "agent_sandbox_policyd=info".into()),
        )
        .with_writer(std::io::stderr)
        .with_target(false)
        .without_time()
        .init();

    let cli = Cli::parse();
    if cli.cleanup_cgroup_freeze {
        agent_sandbox_policyd::cleanup_cgroup_freeze()
            .map_err(|error| std::io::Error::other(error.to_string()))?;
        return Ok(());
    }
    let args = PolicydArgs {
        host_socket: cli.socket,
        sandbox_socket: cli.sandbox_socket,
        proxy_socket: cli.proxy_socket,
        proxy_gid: cli.proxy_gid,
        declarative: cli.declarative,
        export_json: cli.export_json,
        export_nix: if cli.export_nix.is_empty() {
            None
        } else {
            Some(PathBuf::from(cli.export_nix))
        },
        approval_timeout: Duration::from_secs_f64(cli.approval_timeout.max(1.0)),
        interactive_approval: cli.interactive_approval,
        ui_spawn_cmd: cli.ui_spawn_cmd,
        fs_monitor_cmd: cli.fs_monitor_cmd,
        syscall_broker_cmd: cli.syscall_broker_cmd,
    };

    let mut store = PolicyStore::new(args);
    store.enable_cgroup_freezer();
    let store = Arc::new(store);
    store.export_policy_files(agent_sandbox_core::SandboxPaths::default())?;

    let host_socket = store.args().host_socket.clone();
    let sandbox_socket = store.args().sandbox_socket.clone();
    let server = PolicyServer::new(store.clone(), host_socket, sandbox_socket);
    server.run().await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    #[test]
    fn cli_defaults_preserve_standalone_fallbacks() {
        let cli = Cli::try_parse_from(["agent-sandbox-policyd"])
            .expect("standalone invocation has valid defaults");
        assert_eq!(cli.socket, PathBuf::from("/run/agent-sandbox/policy.sock"));
        assert_eq!(
            cli.sandbox_socket,
            PathBuf::from("/run/agent-sandbox/sandbox-policy.sock")
        );
        assert_eq!(
            cli.declarative,
            PathBuf::from("/etc/agent-sandbox/declarative.json")
        );
        assert_eq!(
            cli.export_json,
            PathBuf::from("/var/lib/agent-sandbox/exported-policy.json")
        );
        assert_eq!(cli.export_nix, "");
        assert!((cli.approval_timeout - 300.0).abs() < f64::EPSILON);
        assert!(cli.interactive_approval);
        assert_eq!(cli.ui_spawn_cmd, None);
        assert_eq!(cli.fs_monitor_cmd, None);
        assert_eq!(cli.syscall_broker_cmd, None);
    }

    #[test]
    fn cli_accepts_nix_supplied_launch_facts() {
        let cli = Cli::try_parse_from([
            "agent-sandbox-policyd",
            "--socket",
            "/run/test/policy.sock",
            "--sandbox-socket",
            "/run/test/sandbox-policy.sock",
            "--declarative",
            "/etc/test/declarative.json",
            "--export-json",
            "/var/lib/test/exported-policy.json",
            "--export-nix",
            "/var/lib/test/policy.nix",
            "--approval-timeout",
            "42.5",
            "--no-interactive-approval",
            "--ui-spawn-cmd",
            "/bin/test-ui",
            "--fs-monitor-cmd",
            "/bin/test-fsmon",
            "--syscall-broker-cmd",
            "/bin/test-broker",
        ])
        .expect("explicit launch facts parse");
        assert_eq!(cli.socket, PathBuf::from("/run/test/policy.sock"));
        assert_eq!(
            cli.sandbox_socket,
            PathBuf::from("/run/test/sandbox-policy.sock")
        );
        assert_eq!(cli.declarative, PathBuf::from("/etc/test/declarative.json"));
        assert_eq!(
            cli.export_json,
            PathBuf::from("/var/lib/test/exported-policy.json")
        );
        assert_eq!(cli.export_nix, "/var/lib/test/policy.nix");
        assert!((cli.approval_timeout - 42.5).abs() < f64::EPSILON);
        assert!(!cli.interactive_approval);
        assert_eq!(cli.ui_spawn_cmd, Some(PathBuf::from("/bin/test-ui")));
        assert_eq!(cli.fs_monitor_cmd, Some(PathBuf::from("/bin/test-fsmon")));
        assert_eq!(
            cli.syscall_broker_cmd,
            Some(PathBuf::from("/bin/test-broker"))
        );
    }
}
