//! Agent sandbox policy daemon entry point.

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use agent_sandbox_policyd::{PolicyServer, PolicyStore, PolicydArgs, PolicydError};
use clap::Parser;

#[derive(Parser, Debug)]
#[command(
    name = "agent-sandbox-policyd",
    version,
    about = "Policy daemon that brokers prompts between sandboxed agents and host UI clients",
    long_about = "Long-lived policy daemon for the agent sandbox stack.\n\n\
        Listens on a host-side Unix socket for UI clients (agent-sandbox-approve, \
        agent-sandbox-ui) and on a separate sandbox-side socket for components running \
        inside the bwrap mount namespace (agent-sandbox-nfq, agent-sandbox-syscall-arm, \
        agent-sandbox-fs-arm). Merges declarative policy, per-project policy, and \
        per-session rules into a unified verdict store, then answers Check/Elevate/\
        Filesystem requests and prompts the user for interactive approvals.\n\n\
        EXAMPLES:\n\
        # Run with default NixOS paths.\n\
        agent-sandbox-policyd\n\n\
        # Override the host socket and load policy from a custom JSON file.\n\
        agent-sandbox-policyd \\\n\
            --socket /run/agent-sandbox/policy.sock \\\n\
            --declarative /home/user/.config/agent-sandbox/declarative.json\n\n\
        # Enable interactive approval with a longer timeout and a Nix expression export.\n\
        agent-sandbox-policyd \\\n\
            --interactive-approval \\\n\
            --approval-timeout 600 \\\n\
            --export-nix /var/lib/agent-sandbox/exported-policy.nix"
)]
struct Cli {
    /// Host-side Unix socket path. UI clients (agent-sandbox-approve, agent-sandbox-ui) connect here to register and receive prompts.
    #[arg(
        long,
        value_name = "SOCKET",
        default_value = "/run/agent-sandbox/policy.sock"
    )]
    socket: PathBuf,

    /// Sandbox-side Unix socket path. Components running inside the bwrap mount namespace (agent-sandbox-nfq, agent-sandbox-syscall-arm, agent-sandbox-fs-arm) connect here. Must differ from the host socket.
    #[arg(
        long,
        value_name = "SOCKET",
        default_value = "/run/agent-sandbox/sandbox-policy.sock"
    )]
    sandbox_socket: PathBuf,

    /// Declarative policy JSON file. The lowest-priority policy layer, typically generated by the NixOS module from "agent-sandbox.declarative" settings.
    #[arg(
        long,
        value_name = "PATH",
        default_value = "/etc/agent-sandbox/declarative.json"
    )]
    declarative: PathBuf,

    /// Where the merged policy is written as JSON on startup. Consumed by the bwrap wrapper and by "agent-sandbox-nfq" to bootstrap the in-kernel deny list.
    #[arg(
        long,
        value_name = "PATH",
        default_value = "/var/lib/agent-sandbox/exported-policy.json"
    )]
    export_json: PathBuf,

    /// Optional path to also export the merged policy as a Nix attribute set expression. Empty (the default) disables the Nix export. Used by NixOS rebuilds to regenerate "environment.etc.\"agent-sandbox/policy.nix\"".
    #[arg(long, value_name = "PATH", default_value = "")]
    export_nix: String,

    /// How long (in seconds) to wait for a UI client to answer an approval prompt before denying the request. Fractional values are accepted. The effective wait is clamped to at least 1 second.
    #[arg(long, value_name = "SECONDS", default_value = "300")]
    approval_timeout: f64,

    /// Allow UI clients to receive interactive approval prompts. When disabled, all non-declarative requests are denied without prompting. Useful for headless or CI sandboxes.
    #[arg(long, default_value_t = true)]
    interactive_approval: bool,

    /// Path to the "agent-sandbox-ui" binary. If unset, the daemon falls back to the env var "AGENT_SANDBOX_UI_SPAWN_CMD", then to a built-in default. Used when policyd needs to spawn a transient TTY prompt for a request that arrived with no registered UI.
    #[arg(long, value_name = "PATH", env = "AGENT_SANDBOX_UI_SPAWN_CMD")]
    ui_spawn_cmd: Option<PathBuf>,

    /// Path to the "agent-sandbox-fsmon" binary. If unset, the daemon falls back to the env var "AGENT_SANDBOX_FS_MONITOR_CMD". Used when an "agent-sandbox-fs-arm" request asks for a fanotify monitor to be started in the host mount namespace.
    #[arg(long, value_name = "PATH", env = "AGENT_SANDBOX_FS_MONITOR_CMD")]
    fs_monitor_cmd: Option<PathBuf>,

    /// Path to the "agent-sandbox-syscall-broker" binary. If unset, the daemon falls back to the env var "AGENT_SANDBOX_SYSCALL_BROKER_CMD". Used when an "agent-sandbox-syscall-arm" request needs a host-side seccomp user-notification handler to be spawned.
    #[arg(long, value_name = "PATH", env = "AGENT_SANDBOX_SYSCALL_BROKER_CMD")]
    syscall_broker_cmd: Option<PathBuf>,
}

#[tokio::main]
async fn main() -> Result<(), PolicydError> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "agent_sandbox_policyd=info".into()),
        )
        .with_writer(std::io::stderr)
        .with_target(false)
        .without_time()
        .init();

    let cli = Cli::parse();
    let args = PolicydArgs {
        host_socket: cli.socket,
        sandbox_socket: cli.sandbox_socket,
        declarative: cli.declarative,
        export_json: cli.export_json,
        export_nix: if cli.export_nix.is_empty() {
            None
        } else {
            Some(PathBuf::from(cli.export_nix))
        },
        approval_timeout: Duration::from_secs_f64(cli.approval_timeout.max(1.0)),
        interactive_approval: cli.interactive_approval,
        ui_spawn_cmd: cli.ui_spawn_cmd,
        fs_monitor_cmd: cli.fs_monitor_cmd,
        syscall_broker_cmd: cli.syscall_broker_cmd,
    };

    let store = Arc::new(PolicyStore::new(args));
    store
        .export_policy_files(agent_sandbox_core::SandboxPaths::default())
        .await?;

    let host_socket = store.args().host_socket.clone();
    let sandbox_socket = store.args().sandbox_socket.clone();
    let server = PolicyServer::new(store.clone(), host_socket, sandbox_socket);
    server.run().await?;
    Ok(())
}
