//! Policy store — context.

use std::path::{Path, PathBuf};

use agent_sandbox_core::{
    Policy, ProcessIds, SandboxPaths, context_from_pid, home_from_uid, infer_home_from_paths,
    load_policy, merge_layers, project_policy_paths, read_session_context,
};

use crate::wire::MergeContext;

use super::types::PolicyStore;

impl PolicyStore {
    pub async fn resolve_context(
        &self,
        cwd: Option<String>,
        home: Option<String>,
        project_root: Option<String>,
        pid: Option<u32>,
        uid: Option<u32>,
    ) -> (Option<String>, Option<String>, Option<String>) {
        let file_ctx = read_session_context();
        let mut cwd = cwd.or(file_ctx.cwd);
        let mut home = home.or(file_ctx.home);
        let mut project_root = project_root.or(file_ctx.project_root);

        if let Some(pid) = pid.filter(|p| *p > 0) {
            let (pc, ph, pp) = context_from_pid(pid);
            cwd = cwd.or(pc);
            home = home.or(ph);
            project_root = project_root.or(pp);
        }
        home = home.or_else(|| home_from_uid(uid));

        if cwd.is_some() && home.is_some() && project_root.is_some() {
            return (cwd, home, project_root);
        }

        let inner = self.inner.lock().await;
        for session in inner.ui_clients.values() {
            if let Some(ctx) = inner.ui_context_by_session.get(&session.session_id) {
                cwd = cwd.clone().or_else(|| ctx.cwd.clone());
                home = home.clone().or_else(|| ctx.home.clone());
                project_root = project_root.clone().or_else(|| ctx.project_root.clone());
                if cwd.is_some() && home.is_some() && project_root.is_some() {
                    break;
                }
            }
        }
        drop(inner);

        let path_hints: Vec<&Path> = [project_root.as_deref(), cwd.as_deref()]
            .into_iter()
            .flatten()
            .map(Path::new)
            .collect();
        home = home.or_else(|| infer_home_from_paths(path_hints));
        (cwd, home, project_root)
    }

    pub(crate) fn user_global_path(home: &str) -> PathBuf {
        PathBuf::from(home).join(".config/agent-sandbox/policy.json")
    }

    pub async fn merged_for(&self, ctx: MergeContext) -> Policy {
        let (cwd, home, project_root) = self
            .resolve_context(
                ctx.paths.cwd_string(),
                ctx.paths.home_string(),
                ctx.paths.project_root_string(),
                ctx.ids.pid(),
                ctx.ids.uid(),
            )
            .await;
        let mut layers = vec![load_policy(&self.args.declarative)];
        if let Some(ref home) = home {
            let path = Self::user_global_path(home);
            if path.is_file() {
                layers.push(load_policy(&path));
            }
        }
        for path in project_policy_paths(
            home.as_deref().map(Path::new),
            cwd.as_deref().map(Path::new),
            project_root.as_deref().map(Path::new),
        ) {
            layers.push(load_policy(&path));
        }
        merge_layers(&layers)
    }

    pub async fn export_policy_files(&self, paths: SandboxPaths) -> std::io::Result<()> {
        let merged = self
            .merged_for(MergeContext {
                paths,
                ids: ProcessIds::default(),
            })
            .await;
        if let Some(parent) = self.args.export_json.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let tmp = self.args.export_json.with_extension("tmp");
        std::fs::write(&tmp, serde_json::to_string_pretty(&merged)? + "\n")?;
        std::fs::rename(&tmp, &self.args.export_json)?;

        if let Some(nix_path) = &self.args.export_nix {
            if let Some(parent) = nix_path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            let mut lines = vec![
                "# Generated by agent-sandbox-policyd.".to_string(),
                "{".to_string(),
                "  network.allow = [".to_string(),
            ];
            for rule in &merged.network.allow {
                let host = rule.host.replace('"', "\\\"");
                lines.push(format!(
                    "    {{ host = \"{host}\"; port = {}; }}",
                    rule.port
                ));
            }
            lines.push("  ];".to_string());
            lines.push("  network.deny = [".to_string());
            for rule in &merged.network.deny {
                let host = rule.host.replace('"', "\\\"");
                lines.push(format!(
                    "    {{ host = \"{host}\"; port = {}; }}",
                    rule.port
                ));
            }
            lines.extend(["  ];".to_string(), "}".to_string(), String::new()]);
            let nix_tmp = nix_path.with_extension("tmp");
            std::fs::write(&nix_tmp, lines.join("\n"))?;
            std::fs::rename(&nix_tmp, nix_path)?;
        }
        Ok(())
    }
}
