//! Policy store: context.

use std::path::Path;

use agent_sandbox_core::{
    Policy, ProcessIds, ProjectPolicyContext, SandboxPaths, context_from_pid, home_from_uid,
    load_policy, merge_layers, resolve_policy_write_path, sandbox_session_id_from_pid,
};

use crate::wire::MergeContext;

use super::types::PolicyStore;

fn atomic_write_text(path: &Path, content: &str) -> std::io::Result<()> {
    let target = resolve_policy_write_path(path);
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let tmp = target.with_file_name(format!(
        "{}.tmp",
        target
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("agent-sandbox-export")
    ));
    std::fs::write(&tmp, content)?;
    std::fs::rename(&tmp, &target)?;
    Ok(())
}

impl PolicyStore {
    pub async fn resolve_context(&self, ctx: MergeContext) -> MergeContext {
        let mut paths = SandboxPaths::from_wire(
            ctx.paths.cwd_string(),
            ctx.paths.home_string(),
            ctx.paths.project_root_string(),
        );

        let mut sandbox_session_id = ctx.sandbox_session_id.clone();
        if let Some(pid) = ctx.ids.pid() {
            let ctx = context_from_pid(pid);
            let proc_paths = SandboxPaths::from_wire(ctx.cwd, ctx.home, ctx.project_root);
            paths = proc_paths.merged_with(
                paths.cwd_string(),
                paths.home_string(),
                paths.project_root_string(),
            );
            if sandbox_session_id.is_none() {
                sandbox_session_id = sandbox_session_id_from_pid(pid);
            }
        }

        let mut home = paths.home_string().or_else(|| home_from_uid(ctx.ids.uid()));
        let mut project_root = paths.project_root_string();

        let project = ProjectPolicyContext::new(
            home.as_deref().map(Path::new),
            paths.cwd().map(Path::new),
            project_root.as_deref().map(Path::new),
        );
        if project_root.is_none() {
            project_root = project
                .project_root()
                .map(|path| path.to_string_lossy().into_owned());
        }
        if home.is_none() {
            home = project.home_hint();
        }

        MergeContext {
            paths: SandboxPaths::from_wire(paths.cwd_string(), home, project_root),
            ids: ctx.ids,
            sandbox_session_id,
        }
    }

    pub async fn merged_for(&self, ctx: MergeContext) -> Policy {
        let ctx = self.resolve_context(ctx).await;
        let home_path = ctx.paths.home().map(Path::new);
        let home_str = home_path.and_then(|p| p.to_str());
        let mut layers = vec![load_policy(&self.args.declarative, home_str)];
        for path in ProjectPolicyContext::new(
            home_path,
            ctx.paths.cwd().map(Path::new),
            ctx.paths.project_root().map(Path::new),
        )
        .layer_paths()
        {
            layers.push(load_policy(&path, home_str));
        }
        merge_layers(&layers)
    }

    pub async fn export_policy_files(&self, paths: SandboxPaths) -> std::io::Result<()> {
        let merged = self
            .merged_for(MergeContext {
                paths,
                ids: ProcessIds::default(),
                sandbox_session_id: None,
            })
            .await;
        atomic_write_text(
            &self.args.export_json,
            &(serde_json::to_string_pretty(&merged)? + "\n"),
        )?;

        if let Some(nix_path) = &self.args.export_nix {
            let mut lines = vec![
                "# Generated by agent-sandbox-policyd.".to_string(),
                "{".to_string(),
                "  network.allow = [".to_string(),
            ];
            for rule in &merged.network.allow {
                let host = rule.host.replace('"', "\\\"");
                lines.push(format!(
                    "    {{ host = \"{host}\"; port = {}; }}",
                    rule.port
                ));
            }
            lines.push("  ];".to_string());
            lines.push("  network.deny = [".to_string());
            for rule in &merged.network.deny {
                let host = rule.host.replace('"', "\\\"");
                lines.push(format!(
                    "    {{ host = \"{host}\"; port = {}; }}",
                    rule.port
                ));
            }
            lines.extend(["  ];".to_string(), "}".to_string(), String::new()]);
            atomic_write_text(nix_path, &lines.join("\n"))?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::atomic_write_text;

    #[test]
    fn atomic_write_text_preserves_symlink() {
        let tmp = tempfile::tempdir().unwrap();
        let real_dir = tmp.path().join("dotfiles/home/dot_config/agent-sandbox");
        let link_dir = tmp.path().join("home/.config/agent-sandbox");
        std::fs::create_dir_all(&real_dir).unwrap();
        std::fs::create_dir_all(&link_dir).unwrap();
        let real = real_dir.join("policy.json");
        let link = link_dir.join("policy.json");
        std::os::unix::fs::symlink(&real, &link).unwrap();

        atomic_write_text(&link, "{}\n").unwrap();

        assert!(link.is_symlink());
        assert_eq!(std::fs::read_to_string(real).unwrap(), "{}\n");
    }
}
