//! Policy store — context.

use std::path::Path;

use agent_sandbox_core::{
    Policy, ProcessIds, ProjectPolicyContext, SandboxPaths, context_from_pid, home_from_uid,
    load_policy, merge_layers,
};

use crate::wire::MergeContext;

use super::types::PolicyStore;

impl PolicyStore {
    pub async fn resolve_context(&self, ctx: MergeContext) -> MergeContext {
        let mut paths = SandboxPaths::from_wire(
            ctx.paths.cwd_string(),
            ctx.paths.home_string(),
            ctx.paths.project_root_string(),
        );

        if let Some(pid) = ctx.ids.pid() {
            let (cwd, home, project_root) = context_from_pid(pid);
            let proc_paths = SandboxPaths::from_wire(cwd, home, project_root);
            paths = proc_paths.merged_with(
                paths.cwd_string(),
                paths.home_string(),
                paths.project_root_string(),
            );
        }

        let mut home = paths.home_string().or_else(|| home_from_uid(ctx.ids.uid()));
        let mut project_root = paths.project_root_string();

        let project = ProjectPolicyContext::new(
            home.as_deref().map(Path::new),
            paths.cwd().map(Path::new),
            project_root.as_deref().map(Path::new),
        );
        if project_root.is_none() {
            project_root = project
                .project_root()
                .map(|path| path.to_string_lossy().into_owned());
        }
        if home.is_none() {
            home = project.home_hint();
        }

        MergeContext {
            paths: SandboxPaths::from_wire(paths.cwd_string(), home, project_root),
            ids: ctx.ids,
        }
    }

    pub async fn merged_for(&self, ctx: MergeContext) -> Policy {
        let ctx = self.resolve_context(ctx).await;
        let home_path = ctx.paths.home().map(Path::new);
        let home_str = home_path.and_then(|p| p.to_str());
        let mut layers = vec![load_policy(&self.args.declarative, home_str)];
        for path in ProjectPolicyContext::new(
            home_path,
            ctx.paths.cwd().map(Path::new),
            ctx.paths.project_root().map(Path::new),
        )
        .layer_paths()
        {
            layers.push(load_policy(&path, home_str));
        }
        merge_layers(&layers)
    }

    pub async fn export_policy_files(&self, paths: SandboxPaths) -> std::io::Result<()> {
        let merged = self
            .merged_for(MergeContext {
                paths,
                ids: ProcessIds::default(),
            })
            .await;
        if let Some(parent) = self.args.export_json.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let tmp = self.args.export_json.with_extension("tmp");
        std::fs::write(&tmp, serde_json::to_string_pretty(&merged)? + "\n")?;
        std::fs::rename(&tmp, &self.args.export_json)?;

        if let Some(nix_path) = &self.args.export_nix {
            if let Some(parent) = nix_path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            let mut lines = vec![
                "# Generated by agent-sandbox-policyd.".to_string(),
                "{".to_string(),
                "  network.allow = [".to_string(),
            ];
            for rule in &merged.network.allow {
                let host = rule.host.replace('"', "\\\"");
                lines.push(format!(
                    "    {{ host = \"{host}\"; port = {}; }}",
                    rule.port
                ));
            }
            lines.push("  ];".to_string());
            lines.push("  network.deny = [".to_string());
            for rule in &merged.network.deny {
                let host = rule.host.replace('"', "\\\"");
                lines.push(format!(
                    "    {{ host = \"{host}\"; port = {}; }}",
                    rule.port
                ));
            }
            lines.extend(["  ];".to_string(), "}".to_string(), String::new()]);
            let nix_tmp = nix_path.with_extension("tmp");
            std::fs::write(&nix_tmp, lines.join("\n"))?;
            std::fs::rename(&nix_tmp, nix_path)?;
        }
        Ok(())
    }
}
