[package]
name = "agent-sandbox-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agent-sandbox-sysutil.workspace = true
aya.workspace = true
getrandom.workspace = true
globset.workspace = true
hickory-proto.workspace = true
idna.workspace = true
libc.workspace = true
nix = { workspace = true, features = ["fs", "poll", "socket", "user"] }
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
tracing.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util", "net", "rt", "time"] }
url = { workspace = true }
uuid = { workspace = true }
which.workspace = true

[dev-dependencies]
tokio = {
  workspace = true,
  features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "time",
  ]
}

[lints]
workspace = true
