[package]
name = "agent-sandbox-syscall-arm"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "agent-sandbox-syscall-arm"
path = "src/main.rs"

[dependencies]
agent-sandbox-syscall = { path = "../syscall" }
agent-sandbox-sysutil = { path = "../sysutil" }

libc.workspace = true
nix = { workspace = true, features = ["fs", "process", "signal"] }

[lints]
workspace = true
